/* Local prototype only. Fixtures and browser storage never contact production. */
const STORAGE='fmcg-purchase-ux-demo-20261008-v1';
const stages=[
 ['Waiting for P.O.','待采购单','Enter Supplier P.O.','输入供应商采购单','Purchase'],
 ['Waiting For Supplier Inv','待供应商发票','Submit Payment Documents','提交付款文件','Admin'],
 ['Waiting for Account Receipt','待财务签收','Acknowledge Documents','确认收到文件','Account'],
 ['Waiting for Payment','待付款','Record Payment','记录付款结果','Account'],
 ['Waiting for Purchase Noted','待采购确认','Acknowledge Payment','确认付款通知','Purchase'],
 ['Waiting for Goods','待来货','Confirm Incoming Qty','确认实收数量','Warehouse'],
 ['Waiting for Repacking','待包装','Confirm Repacking','确认包装完成','Warehouse'],
 ['Waiting for Sales Invoice','待销售发票','Enter Sales Invoice','登记销售发票','Admin'],
 ['Waiting for Shipment','待发货','Confirm Shipment','确认发货','Coordinator']
];
const products=[['8852756303056','CORN FLAKES','150G × 18'],['9556404007035','LEMON SODA','320ML × 24'],['20916031110','PEANUT CRACKERS','(40G × 20) × 8'],['20916082006','ORIENTAL MIX','(150G × 10) × 6'],['9556031204722','MULTI PURPOSE CLEANER','1.5L × 6'],['9550000000006','MANGO DRINK','250ML × 24'],['9550000000007','COCONUT MILK','400ML × 24'],['9550000000008','TOMATO SAUCE','340G × 24'],['9550000000009','INSTANT NOODLES','75G × 30'],['9550000000010','ORANGE CORDIAL','2L × 6']];
function seed(){const customers=[{id:'DEMO-AVATA',name:'AVATA',currency:'MYR'},{id:'DEMO-BERJAYA',name:'BERJAYA',currency:'MYR'},{id:'DEMO-DUDU',name:'DUDU',currency:'MYR'},{id:'DEMO-ALPHA',name:'ALPHA RETAIL',currency:'MYR'}];const today=new Date();today.setHours(11,35,0,0);const tasks=[];for(let i=0;i<30;i++){let p=products[i%10];const done=Array(9).fill(false);done[0]=i>=3&&i<8;tasks.push({id:`T-AV-${String(i+1).padStart(4,'0')}`,customerId:'DEMO-AVATA',orderId:'O-AV-012',barcode:p[0],name:p[1],packing:p[2],ord:[50,20,30,40,20][i%5],requested:[50,20,30,40,20][i%5],inc:null,supplier:i%10<3?'Supplier A':`Supplier ${['B','C','D','E','F'][i%5]}`,price:['1.42','25.56','2.00%','0.00%','0'],po:done[0]?'NC-PO-012':'',done,archived:false,risk:null,wasRisk:false,seq:i,receivedAt:today.toISOString(),updatedAt:today.toISOString(),updatedBy:'Law',history:[{kind:'Order received',at:today.toISOString(),by:'Law',detail:'采购意向接入 · 示例'}]});if(done[0]){tasks.at(-1).history.push({kind:'PO merged',at:new Date(today.getTime()+600000).toISOString(),by:'Yeoyo',detail:'NC-PO-012'});tasks.at(-1).updatedAt=new Date(today.getTime()+600000).toISOString();tasks.at(-1).updatedBy='Yeoyo';}}
for(let i=0;i<3;i++){let p=products[i];const done=[true,true,true,true,i!==1,false,false,false,false];tasks.push({id:`T-BJ-${i+1}`,customerId:'DEMO-BERJAYA',orderId:'O-BJ-008',barcode:p[0],name:p[1],packing:p[2],ord:50,requested:50,inc:i===0?40:null,supplier:'Supplier A',price:['1.42','25.56','2.00%','0.00%','0'],po:'NC-PO-008',done,archived:false,risk:i===0?{reason:'Supplier short delivery / 供应商少送',note:'供应商预计下批补送10箱。'}:null,wasRisk:i===0,seq:i,receivedAt:today.toISOString(),updatedAt:today.toISOString(),updatedBy:'Hia',history:[{kind:'Order received',at:today.toISOString(),by:'Law',detail:'原始订单50 CTN'},...(i===0?[{kind:'Incoming Qty Confirmed',at:new Date(today.getTime()+1800000).toISOString(),by:'Hia',detail:'ord 50 / inc 40 · Risk'}]:[])]});}
return {customers,tasks,paymentRequests:[{id:'PAY-001',po:'NC-PO-008',customerId:'DEMO-BERJAYA',amount:1000,paid:600,currency:'MYR',urgent:false,reason:''},{id:'PAY-002',po:'NC-PO-008',customerId:'DEMO-BERJAYA',amount:400,paid:0,currency:'MYR',urgent:true,reason:'供应商要求尽快安排余款。'}]};}
let db;try{db=JSON.parse(localStorage.getItem(STORAGE));if(!db?.tasks||!db?.customers)throw Error();}catch{db=seed();}
// Explicit UX-only factor fixtures. Real Pointbase is not connected.
const DEMO_EA=[18,24,160,60,6,24,24,24,30,6];
for(const t of db.tasks)if(t.ea===undefined){t.ea=DEMO_EA[products.findIndex(p=>p[0]===t.barcode)];t.eaSource='DEMO';}
let lastSaved=structuredClone(db);
let view='dashboard',customerId='DEMO-AVATA',selected=new Set(),filter={query:'',supplier:'',order:'',stage:'',risk:false},drafts=new Map(),sequenceDraft=null,held=null,highlightTimer,toastTimer,dragId=null;
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),content=document.querySelector('#dialogContent');
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const active=()=>db.tasks.filter(t=>!t.archived);const scope=()=>active().filter(t=>t.customerId===customerId).sort((a,b)=>a.seq-b.seq);const find=id=>db.tasks.find(t=>t.id===id);
function persist(){const saved=structuredClone(db);if(sequenceDraft)sequenceDraft.forEach((id,i)=>{const t=saved.tasks.find(t=>t.id===id);if(t)t.seq=i;});try{localStorage.setItem(STORAGE,JSON.stringify(saved));lastSaved=saved;return true;}catch{db=structuredClone(lastSaved);toast('本地保存失败，输入保留；请重试或取消。');return false;}}function now(){return new Date().toISOString();}function event(t,kind,detail){const at=now();t.history.push({kind,detail,at,by:'Law'});t.updatedAt=at;t.updatedBy='Law';}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',4500);}
function fullDate(at){const d=new Date(at),pad=n=>String(n).padStart(2,'0');return `${pad(d.getDate())}-${pad(d.getMonth()+1)}-${String(d.getFullYear()).slice(-2)} ${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function shortDate(at,by){const d=new Date(at),today=new Date(),label=d.toDateString()===today.toDateString()?'Today':fullDate(at).split(' ')[0];return `${label} ${String(d.getHours()).padStart(2,'0')}.${String(d.getMinutes()).padStart(2,'0')} fr ${by}`;}
function unfinished(t,i){return !t.done[i];}function next(t){return t.done.findIndex((x,i)=>i!==4&&!x);}function counts(rows){return stages.map((_,i)=>rows.filter(t=>unfinished(t,i)).length);}
function costResult(values,ea,basis='ctn'){let b;if(basis==='pc'){if(!Number.isFinite(Number(ea))||Number(ea)<=0||!validatePrice(values[0],0))return {b:null,f:null};b=Number(ea)*Number(values[0]);}else{if(!validatePrice(values[1],1))return {b:null,f:null};b=Number(values[1]);}if(!values.slice(2).every((v,i)=>validatePrice(v,i+2)))return {b,f:null};const f=b*(1-parseFloat(values[2])/100)*(1-parseFloat(values[3])/100)-Number(values[4]);return {b:Math.round((b+Number.EPSILON)*100)/100,f:Math.round((f+Number.EPSILON)*100)/100};}
function priceBasis(t){return drafts.get(t.id)?.priceBasis||t.priceBasis||'ctn';}
function refreshCost(id){const t=find(id),r=costResult(price(t),t.ea,priceBasis(t)),row=document.querySelector(`tr[data-id="${id}"]`);if(!row)return;const b=row.querySelector('[data-field="1"]');if(b&&priceBasis(t)==='pc')b.value=r.b===null?'—':r.b.toFixed(2);const net=row.querySelector('.net');net.textContent=r.f===null?'—':r.f.toFixed(2);net.classList.toggle('negative',r.f!==null&&r.f<0);if(drafts.has(id))drafts.get(id).price[1]=r.b===null?'':r.b.toFixed(2);}
function price(t){return drafts.get(t.id)?.price||t.price;}function supplier(t){return drafts.get(t.id)?.supplier??t.supplier;}
function matching(){return scope().filter(t=>(!filter.query||[t.barcode,t.name,t.id,t.po,t.orderId].join(' ').toLowerCase().includes(filter.query.toLowerCase()))&&(!filter.supplier||supplier(t)===filter.supplier)&&(!filter.order||t.orderId===filter.order)&&(filter.stage===''||unfinished(t,Number(filter.stage)))&&(!filter.risk||t.risk));}
const visibleStageIndexes=[0,1,2,3,5,6,8];
// GP is a read-only CMS projection; this room does not calculate profit.
function projectedGp(t){return t.gp==null||String(t.gp).trim()===''?null:Number.isFinite(Number(t.gp))?Number(t.gp):null;}
function gpMarkup(t){const gp=projectedGp(t);return gp===null?'—':esc(t.gp);}
function rowNumber(id){return String(scope().findIndex(t=>t.id===id)+1).padStart(3,'0');}
function riskSummary(){const rows=scope().filter(t=>projectedGp(t)!==null&&projectedGp(t)<0||t.risk);openDialog('RISK / 高风险交易',`${rows.length} rows`,rows.length?`<table class="rowlist"><thead><tr><th style="width:12%">ROW</th><th>DESCRIPTION</th><th style="width:17%">GP</th><th style="width:27%">RISK</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${rowNumber(t.id)}</td><td><b>${esc(t.name)}</b><small>${esc(t.barcode)}</small></td><td class="${projectedGp(t)!==null&&projectedGp(t)<0?'negative':''}">${gpMarkup(t)}</td><td>${[projectedGp(t)!==null&&projectedGp(t)<0?'Negative GP / 负利润':'',t.risk?'Receipt Risk / 来货差异':''].filter(Boolean).join('<br>')}</td></tr>`).join('')}</tbody></table>`:'<div class="note">目前没有已知的高风险交易。<br>No known high-risk rows.</div>');}
function customerName(c){return c.id==='DEMO-AVATA'?'AVATA TRADING PTE LTD':c.name;}
function receivedMarkup(t){const by=t.history.find(e=>e.kind==='Order received')?.by||'Law';return `<div class="date">${shortDate(t.receivedAt,by).split(' fr ')[0]}</div><small>fr ${esc(by.toUpperCase())}</small>`;}
function track(rows){return `<section class="track" aria-label="Pending workload">${visibleStageIndexes.map(i=>{const n=counts(rows)[i];return `<div class="trackitem"><button class="circle ${n===0?'zero':''}" data-hold="${i}" aria-label="${stages[i][0]} ${n}">${n}</button><span class="tracklabel">${stages[i][0]}<small>${stages[i][1]}</small></span></div>`;}).join('')}</section>`;}
function heading(title,sub,buttons=''){return `<div class="heading"><div><div class="eyebrow">PURCHASE / ${view.toUpperCase()}</div><h1>${title}</h1><span class="muted">${sub}</span></div><div class="actions">${buttons}</div></div>`;}
function metrics(rows){return `<section class="metrics"><div class="metric"><span>Active Orders / 进行中订单</span><b>${new Set(rows.map(t=>t.orderId)).size}</b><small class="muted">不同 Order ID</small></div><div class="metric"><span>Purchase Tasks / 采购任务</span><b>${rows.length}</b><small class="muted">产品行任务 ID</small></div><div class="metric"><span>Unpaid Requests / 未完成付款申请</span><b>${db.paymentRequests.filter(p=>p.paid<p.amount).length}</b><small class="muted">每次申请独立</small></div><div class="metric red"><span>Receipt Risk / 来货问题</span><b>${rows.filter(t=>t.risk).length}</b><small class="muted">有问题的产品行</small></div></section>`;}
function customerTable(){return `<table class="directory"><thead><tr><th style="width:37%">Customer / 客户</th><th>Tasks / 任务</th><th>Orders / 订单</th><th>Risk</th><th></th></tr></thead><tbody>${db.customers.map(c=>{const rows=active().filter(t=>t.customerId===c.id);return `<tr><td><button class="customerlink" data-customer="${c.id}">${c.name}</button></td><td>${rows.length?`<span class="bubble">${rows.length}</span>`:'0'}</td><td>${new Set(rows.map(t=>t.orderId)).size}</td><td>${rows.filter(t=>t.risk).length||'—'}</td><td><button class="btn" data-customer="${c.id}">Open Room →</button></td></tr>`;}).join('')}</tbody></table>`;}
function render(){clearHold();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard'){app.innerHTML=heading('Purchase Dashboard','Law · Purchase部门 · 本地示例',`<button class="btn primary" data-view="customers">Customers Job →</button>`)+metrics(active())+track(active())+`<div class="grid"><section class="panel"><div class="panelhead"><h2>Customers with ongoing work / 客户任务</h2></div>${customerTable()}</section><section class="panel"><div class="panelhead"><h2>Attention / 待跟进</h2></div><table class="directory"><thead><tr><th>Customer / Task</th><th>Next action</th><th></th></tr></thead><tbody>${active().filter(t=>t.risk).map(t=>`<tr><td>${db.customers.find(c=>c.id===t.customerId).name}<small>${t.id}</small></td><td>${t.risk?'Risk · ord 50 / inc 40':'Acknowledge Payment / 确认付款通知'}</td><td><button class="btn" data-customer="${t.customerId}">Open →</button></td></tr>`).join('')||'<tr><td colspan="3">No urgent follow-up / 暂无紧急事项</td></tr>'}</tbody></table></section></div>`;}
else if(view==='customers'){app.innerHTML=heading('Customers Job','全部客户 · 红泡泡按未归档产品任务ID计数')+`<div class="tools"><input id="customerSearch" placeholder="Search customer / 搜索客户"></div><section class="panel"><div class="panelhead"><h2>Customer directory</h2><span class="muted">${db.customers.length} customers</span></div>${customerTable()}</section>`;}
else if(view==='room')renderRoom();else if(view==='po')renderPo();else if(view==='payments')renderPayments();else renderHistory();}
function renderRoom(){const c=db.customers.find(c=>c.id===customerId),rows=scope(),shown=matching(),suppliers=[...new Set(rows.map(t=>supplier(t)))],orders=[...new Set(rows.map(t=>t.orderId))];app.innerHTML='<section class="roomhead">'+heading(customerName(c),`${rows.length} Tasks · ${orders.length} Orders · ${suppliers.length} Suppliers`)+track(rows)+'</section>'+`<div class="tools"><select id="supplierFilter"><option value="">ALL SUPPLIER</option>${suppliers.map(s=>`<option ${filter.supplier===s?'selected':''}>${s}</option>`).join('')}</select><select id="stageFilter"><option value="">WAITING LIST</option>${stages.map((s,i)=>i===4?'':`<option value="${i}" ${String(i)===filter.stage?'selected':''}>${s[0]}</option>`).join('')}</select><button class="btn risk-summary" id="riskFilter"><span class="risk-icon" aria-hidden="true">▲<b>!</b></span> RISK</button><span class="count" id="visibleCount">${shown.length} / ${rows.length} rows · 点击圆圈高亮3秒</span></div><section class="panel"><div class="panelhead"><h2>Purchase Tasks · ${rows.length}</h2><span class="muted">NET自动计算 · 示例EA</span></div><div class="selection"><span id="selectedLabel">${selected.size} selected / 已选</span><div class="actions"><button class="btn primary unified-save" id="saveEdits" ${(drafts.size||sequenceDraft)?'':'disabled'}>Save</button><button class="btn" id="moveSelected">Move selected ↕</button><button class="btn" id="saveOrder" ${sequenceDraft?'':'disabled'}>Save row order</button><button class="btn" id="cancelOrder" ${sequenceDraft?'':'disabled'}>Cancel move</button><button class="btn" id="savePrices" ${drafts.size?'':'disabled'}>Save price edits</button><button class="btn" id="cancelPrices" ${drafts.size?'':'disabled'}>Cancel edits</button></div></div><div class="tablewrap"><table><colgroup>${[3.5,2.5,7,8,20.5,7,5,4,4,4,4,3.5,4.5,7,12,3].map(w=>`<col style="width:${w}%">`).join('')}</colgroup><thead><tr>${['<button class="btn" id="clearSelection">Clear</button>','ROW','Order Received','Waiting','Description','Supplier','Qty','LP/PC','LP/CTN','Disc.1','Disc.2','Disc.3','Net Cost','Our P.O. No.','Path','GP'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody id="taskRows">${rowMarkup(shown)}</tbody></table></div><div class="foot"><span>任务ID固定 · 按圈未完成数不可相加</span><span>示例保存：此浏览器 · 原始客户数量不受实收影响</span></div></section><div class="hint">Purchase只执行自己的动作；其它部门任务可查看与跟进。计算器使用隐藏示例EA，尚未连接Pointbase；价格保存不代表已经完成采购步骤。</div>`;fitItemNames();}

function fitItemNames(){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');for(const el of document.querySelectorAll('#taskRows .itemname')){const name=el.dataset.name,packing=el.dataset.packing,full=name+' · '+packing,width=el.clientWidth;if(!width)continue;const style=getComputedStyle(el),regular='400 '+style.fontSize+' '+style.fontFamily,bold='700 '+style.fontSize+' '+style.fontFamily;const measure=(start,end)=>{let size=0;for(let i=start;i<end;i++){ctx.font=i<name.length?bold:regular;size+=ctx.measureText(full[i]).width;}return size;};let firstEnd=full.length;for(let i=1;i<=full.length;i++)if(measure(0,i)>width){firstEnd=i-1;const space=full.lastIndexOf(' ',firstEnd);if(space>0)firstEnd=space;break;}let lastEnd=full.length,truncated=false;if(firstEnd<full.length){ctx.font=regular;const dots=ctx.measureText('…').width;for(let i=firstEnd+1;i<=full.length;i++)if(measure(firstEnd,i)+dots>width/2){lastEnd=i-1;truncated=true;break;}}const part=(a,b)=>{const split=Math.max(a,Math.min(b,name.length));return esc(full.slice(a,split))+'<span class="packing">'+esc(full.slice(split,b))+'</span>';};el.innerHTML=part(0,firstEnd)+(firstEnd<full.length?'<br>'+part(firstEnd,lastEnd)+(truncated?'…':''):'');}}
function rowMarkup(rows){return rows.map(t=>{const i=next(t),s=stages[i],latest=[...t.history].sort((a,b)=>new Date(b.at)-new Date(a.at))[0],values=[...price(t)],result=costResult(values,t.ea,priceBasis(t));values[1]=result.b===null?'—':result.b.toFixed(2);if(Number(values[4])===0)values[4]='0.00';return `<tr data-id="${t.id}" class="${selected.has(t.id)?'selected':''}"><td><div class="row-controls"><button class="handle" draggable="true" data-drag="${t.id}" aria-label="Move ${t.id}">⠿</button><input class="check rowcheck" type="checkbox" data-id="${t.id}" aria-label="Select ${t.id}" ${selected.has(t.id)?'checked':''}></div></td><td class="row-number">${rowNumber(t.id)}</td><td>${receivedMarkup(t)}</td><td><button class="mission" data-waiting="${t.id}">${s?i===0?'Enter P.O. No.':s[0]:'Completed'}</button></td><td><span class="barcode">${t.barcode}</span><b class="itemname" data-name="${esc(t.name)}" data-packing="${esc(t.packing)}">${esc(t.name)} <span class="packing">${esc(t.packing)}</span></b></td><td><select class="supplier" data-supplier="${t.id}" aria-label="Supplier ${t.id}">${['Supplier A','Supplier B','Supplier C','Supplier D','Supplier E','Supplier F'].map(s=>`<option ${supplier(t)===s?'selected':''}>${s}</option>`).join('')}</select></td><td><div class="qty-pair"><button class="qty-order" data-qty="${t.id}" aria-label="Order quantity ${t.id}">${t.ord}</button><span aria-hidden="true">|</span><button class="${t.inc==null?'qty-empty':t.inc===t.ord?'qty-match':'qty-mismatch'}" data-receipt="${t.id}" aria-label="Incoming quantity ${t.id}">${t.inc??'—'}</button></div></td>${values.map((v,j)=>`<td><input class="money" data-price="${t.id}" data-field="${j}" aria-label="${['LP/PC','LP/CTN','DISC1','DISC2','DISC3'][j]} ${t.id}" value="${esc(v)}"  inputmode="decimal"></td>`).join('')}<td><b class="net ${result.f!==null&&result.f<0?'negative':''}">${result.f===null?'—':result.f.toFixed(2)}</b></td><td><div class="po"><input class="po-field" data-po="${t.id}" aria-label="PO field ${t.id}" value="${esc(t.po)}" placeholder="P.O. number" readonly></div></td><td><button class="path" data-path="${t.id}"><strong>${esc(latest.kind)} on</strong><br>${fullDate(latest.at)} by ${esc(latest.by)}</button>${t.risk?`<button class="risk" data-risk="${t.id}">● Risk</button>`:t.wasRisk&&t.inc===t.ord?'<span class="good">Problem Solved</span>':''}</td><td><b class="gp ${projectedGp(t)!==null&&projectedGp(t)<0?'negative':''}">${gpMarkup(t)}</b></td></tr>`;}).join('')||'<tr><td colspan="16" class="empty">No matching tasks / 没有匹配的任务</td></tr>';}
function renderPo(){const groups=new Map();for(const t of active().filter(t=>t.po)){if(!groups.has(t.po))groups.set(t.po,[]);groups.get(t.po).push(t);}app.innerHTML=heading('Supplier P.O.','外部供应商采购单 · 只登记关联，不开正式单据')+`<section class="panel"><table class="directory"><thead><tr><th>P.O. Number</th><th>Tasks / 产品任务</th><th>ord / CTN</th><th>Supplier</th><th></th></tr></thead><tbody>${[...groups].map(([po,rows])=>`<tr><td><b>${esc(po)}</b></td><td>${rows.length}</td><td>${rows.reduce((n,t)=>n+t.ord,0)}</td><td>${[...new Set(rows.map(t=>t.supplier))].join(', ')}</td><td><button class="btn" data-po-details="${esc(po)}">Details ↗</button></td></tr>`).join('')}</tbody></table></section>`;}
function renderPayments(){app.innerHTML=heading('Payment Follow-up','Account负责付款，Purchase仅跟进 · 每次申请独立')+`<section class="panel"><table class="directory"><thead><tr><th>Request ID</th><th>P.O.</th><th>Requested</th><th>Paid</th><th>Balance</th><th>Urgent / 催款</th><th></th></tr></thead><tbody>${db.paymentRequests.map(p=>`<tr><td>${p.id}</td><td>${p.po}</td><td>${p.currency} ${p.amount.toFixed(2)}</td><td>${p.paid.toFixed(2)}</td><td>${(p.amount-p.paid).toFixed(2)}</td><td>${p.urgent?'<span class="bubble">待跟进</span>':'—'}</td><td><button class="btn" data-payment="${p.id}">Details</button></td></tr>`).join('')}</tbody></table></section>`;}
function renderHistory(){const events=db.tasks.flatMap(t=>t.history.map(e=>({...e,taskId:t.id,customerId:t.customerId}))).sort((a,b)=>new Date(b.at)-new Date(a.at));app.innerHTML=heading('Activity History','示例动作记录 · 首次时间与后续动作分别保留')+`<section class="panel"><table class="directory"><thead><tr><th>Task</th><th>Action</th><th>Time / Actor</th><th>Detail</th><th></th></tr></thead><tbody>${events.map(e=>`<tr><td>${e.taskId}</td><td>${esc(e.kind)}</td><td>${fullDate(e.at)} by ${esc(e.by)}</td><td>${esc(e.detail)}</td><td><button class="btn" data-path="${e.taskId}">PATH</button></td></tr>`).join('')}</tbody></table></section>`;}
function openDialog(title,sub,body,buttons='',onSave=null){clearHold();content.innerHTML=`<div class="dialoghead"><div><div class="eyebrow">LOCAL UX · 示例操作</div><h2>${title}</h2><span class="muted">${sub}</span></div><button class="close" id="closeDialog" aria-label="Close">×</button></div><div class="dialogbody">${body}<div class="error" id="dialogError" role="alert"></div></div><div class="dialogfoot"><span class="muted">不连接真实数据</span><div class="actions"><button class="btn" id="cancelDialog">${onSave?'Cancel':'Close'}</button>${buttons}</div></div>`;modal.showModal();content.querySelector('#closeDialog').onclick=closeDialog;content.querySelector('#cancelDialog').onclick=closeDialog;if(onSave)content.querySelector('#dialogSave').onclick=onSave;}
function closeDialog(){modal.close();content.innerHTML='';}function error(m){content.querySelector('#dialogError').textContent=m;}
function listRows(rows){return `<table class="rowlist"><colgroup><col style="width:25%"><col style="width:55%"><col style="width:20%"></colgroup><thead><tr><th>BARCODE</th><th>DESCRIPTION</th><th>QTY · ord</th></tr></thead><tbody>${rows.map(t=>`<tr><td>${t.barcode}<small>${t.id}</small></td><td><b>${t.name}</b><small>${t.packing}</small></td><td>${t.ord} CTN</td></tr>`).join('')}</tbody></table>`;}
function openPo(id){if(drafts.size||sequenceDraft){toast('请先保存或取消价格/排列编辑。');return;}if(selected.size&&!selected.has(id)){toast('请点击已勾选行的P.O.输入框，或先清除选择。');return;}const rows=selected.size?scope().filter(t=>selected.has(t.id)):[find(id)];if(rows.some(t=>t.po)){openDialog('Existing P.O. / 已关联采购单','重新关联规则尚待确认',listRows(rows)+`<div class="note">${rows.map(t=>t.id+' → '+(t.po||'未登记')).join('<br>')}<br>本原型不覆盖已有号码；请选择未登记P.O.的任务。</div>`);return;}openDialog('Merge into one P.O. / 关联同一采购单',`${rows.length} selected tasks · ${rows.reduce((n,t)=>n+t.ord,0)} CTN`,listRows(rows)+`<div class="note">${[...new Set(rows.map(t=>t.supplier))].join(' / ')} · 每行任务ID保留</div><div class="field"><label>P.O. NUMBER *</label><input id="poNumber" maxlength="80" placeholder="Enter supplier P.O. number"></div>`,'<button class="btn primary" id="dialogSave">SAVE</button>',()=>{const po=content.querySelector('#poNumber').value.trim();if(!po)return error('请输入P.O.号码。');if(new Set(rows.map(t=>t.supplier)).size>1)return error('已选任务包含不同供应商。此关联规则待确认，请先选择同一供应商。');for(const row of rows){const t=find(row.id);t.po=po;t.done[0]=true;event(t,'PO merged',`${po} · ${rows.length} independent tasks linked`);}if(!persist())return;closeDialog();render();toast(`示例已保存：${rows.length}行关联${po}，任务ID保留。`);});}
function pathDialog(id){const t=find(id),hist=[...t.history].sort((a,b)=>new Date(b.at)-new Date(a.at));openDialog('PATH',`${t.id} · ${t.barcode} · ${t.name}`,`<div class="timeline">${hist.map(e=>`<div class="event"><b>${esc(e.kind)}</b><small>on ${fullDate(e.at)} by ${esc(e.by)}</small><p>${esc(e.detail)}</p></div>`).join('')}</div>${t.risk?'<div class="notice">仍为Risk：ord '+t.ord+' / inc '+t.inc+'。实收记录不等于已收齐。</div>':''}`);}
function riskDialog(id){let t=find(id);if(!t.risk){pathDialog(id);return;}const reasons=['Supplier short delivery / 供应商少送','Supplier excess delivery / 供应商多送','Damaged goods / 货损','Wrong items / 货不对版','Other / 其它'];openDialog('Receipt Risk',`${t.barcode} · ${t.name}`,`<div class="stats"><div><span>ord</span><b>${t.ord}</b></div><div><span>inc · cumulative</span><b>${t.inc}</b></div><div class="red"><span>Difference</span><b>${t.inc-t.ord}</b></div></div><div class="field"><label>Reason *</label><select id="riskReason"><option value="">选择原因</option>${reasons.map(r=>`<option ${t.risk.reason===r?'selected':''}>${r}</option>`).join('')}</select></div><div class="field"><label>Additional note</label><textarea id="riskNote">${esc(t.risk.note)}</textarea></div><span class="badgeblue">Sales Room</span> <span class="badgeblue">Account Room</span><div class="notice" style="margin-top:15px">补送预期仍是Risk。后续累计补齐才Problem Solved；不修改客户Committed Qty。</div>`,'<button class="btn danger" id="dialogSave">Send Note</button>',()=>{t=find(id);const reason=content.querySelector('#riskReason').value,note=content.querySelector('#riskNote').value.trim();if(!reason)return error('请选择Risk原因。');t.risk={reason,note};t.wasRisk=true;event(t,'Risk Note Sent',`${reason} · ${note} · Sales Room + Account Room（示例通知）`);if(!persist())return;closeDialog();render();toast('示例通知已记录；未发送给真实Sales／Account。');});}
function actionDialog(id){let t=find(id);const i=next(t),s=stages[i];if(!s)return pathDialog(id);if(i===0)return openPo(id);if(s[4]!=='Purchase')return openDialog(s[0]+' / '+s[1],t.id,`<p>${s[3]}由 <b>${s[4]}</b> 在自己的Room操作。</p><div class="note">Purchase可跟进，但不能代替此部门执行。此步骤尚未完成，仍计入待办。</div>`);if(i===4)openDialog('Acknowledge Payment / 确认付款通知',t.id,`<p>查看Account回报后，记录采购员Noted。</p><div class="note">这是示例已有付款记录；部分付款与真实回报的规则在数据接入时另行核实。</div>`,'<button class="btn primary" id="dialogSave">Noted</button>',()=>{t=find(id);t.done[4]=true;event(t,'Payment Noted','Purchase acknowledged sample payment');if(!persist())return;closeDialog();render();toast('示例采购确认已记录。');});}
function qtyDialog(id){let t=find(id);openDialog('Order Qty / 订单数量',`${t.id} · Requested Qty ${t.requested} CTN`,`${t.risk?'<div class="notice">此行有Risk。调整ord不解除Risk，不代替后续补送。</div>':''}<div class="field"><label>ord *</label><input id="qtyValue" type="number" min="0" step="1" value="${t.ord}"></div><div class="field"><label>Reason *</label><textarea id="qtyReason"></textarea></div>`,'<button class="btn primary" id="dialogSave">SAVE</button>',()=>{t=find(id);const raw=content.querySelector('#qtyValue').value,n=Number(raw),reason=content.querySelector('#qtyReason').value.trim();if(!raw||!Number.isInteger(n)||n<0)return error('请输入非负整数数量。');if(!reason)return error('数量调整必须填写Reason。');if(n===t.ord)return error('数量没有变化。');const previous=t.ord;t.ord=n;event(t,'Order Qty Updated',`${previous} → ${n} CTN · Reason: ${reason} · Requested ${t.requested} unchanged`);if(!persist())return;closeDialog();render();toast('示例ord已保存；没有回传真实Buyer／Sales。');});}
function receiptDialog(id){const t=find(id);openDialog('Incoming Qty / 实收记录',`${t.id} · Warehouse负责`,`${listRows([t])}<div class="stats"><div><span>ord</span><b>${t.ord}</b></div><div><span>inc · cumulative received</span><b>${t.inc??'—'}</b></div></div><div class="note">实收由Warehouse在自己的Room登记。Purchase原型提供只读查看与Risk通知，不提供代录仓库数量按钮。</div>${t.risk?'<div class="notice">当前Risk，后续累计补齐才解决。</div>':''}`);}
function moveDialog(){if(!selected.size)return toast('先勾选要移动的行。');openDialog('Move selected tasks / 移动已选任务',`${selected.size} selected · IDs retained`,`<div class="field"><label>Destination</label><select id="moveTarget"><option value="top">Top / 移到顶部</option><option value="bottom">Bottom / 移到底部</option>${scope().filter(t=>!selected.has(t.id)).map(t=>`<option value="${t.id}">Before ${t.id} · ${t.name}</option>`).join('')}</select></div><div class="note">仅调整排列，稍后点击Save。Buyer／Sales顺序不会改变。</div>`,'<button class="btn primary" id="dialogSave">Apply move</button>',()=>{if(!sequenceDraft)sequenceDraft=scope().map(t=>t.id);const all=scope(),moving=all.filter(t=>selected.has(t.id)),rest=all.filter(t=>!selected.has(t.id)),target=content.querySelector('#moveTarget').value,pos=target==='top'?0:target==='bottom'?rest.length:rest.findIndex(t=>t.id===target);rest.splice(pos,0,...moving);rest.forEach((t,i)=>t.seq=i);closeDialog();renderRoom();toast('示例排列已调整，点击Save保存。');});}
function validatePrice(v,i){const s=v.trim();if(i<2)return /^\d+(\.\d{1,2})?$/.test(s);if(i<4)return /^\d+(\.\d{1,2})?%?$/.test(s)&&parseFloat(s)<=100;return /^\d+(\.0{1,2})?$/.test(s);}
function formatPrice(v,i){return i<2?Number(v).toFixed(2):i<4?parseFloat(v).toFixed(2)+'%':Number(v)===0?'0.00':String(Number(v));}
function draft(id){if(!drafts.has(id)){const t=find(id);const values=[...t.price],r=costResult(values,t.ea,t.priceBasis||'ctn');values[1]=r.b===null?'':r.b.toFixed(2);drafts.set(id,{price:values,supplier:t.supplier,priceBasis:t.priceBasis||'ctn'});}return drafts.get(id);}
function savePrices(){for(const [id,d]of drafts){if(d.price[0].trim()&&!validatePrice(d.price[0],0)){toast(`${id}：LP/PC须为两位小数或留空。`);return;}const r=costResult(d.price,find(id).ea,d.priceBasis);if(r.f===null){toast(`${id}：请输入LP/CTN，或提供LP/PC及EA；Disc.1/2须为0–100%，Disc.3须为整数。`);return;}}for(const [id,d]of drafts){const t=find(id),r=costResult(d.price,t.ea,d.priceBasis);t.price=d.price.map((v,i)=>i===0&&!v.trim()?'':i===1?r.b.toFixed(2):formatPrice(v,i));t.priceBasis=d.priceBasis;t.supplier=d.supplier;event(t,'Price Inputs Saved',`Calculator inputs saved · ${d.priceBasis==='pc'?'EA × LP/PC':'Entered LP/CTN'} · sequential percentages then Disc.3`);}if(!persist())return;drafts.clear();render();toast('示例计算器已保存；EA仍为示例值。');}
function navigate(target,cid){if(drafts.size||sequenceDraft){openDialog('Unsaved edits / 未保存编辑','先完成当前编辑',`<p>请先保存或取消价格／排列编辑，再切换页面或客户。</p>`);return;}if(cid&&cid!==customerId){customerId=cid;selected.clear();filter={query:'',supplier:'',order:'',stage:'',risk:false};}view=target;render();}
function clearHold(){clearTimeout(highlightTimer);held=null;document.querySelectorAll('tr.highlight').forEach(r=>r.classList.remove('highlight'));}
function hold(i){clearTimeout(highlightTimer);held=i;document.querySelectorAll('tr[data-id]').forEach(r=>r.classList.toggle('highlight',unfinished(find(r.dataset.id),i)));if(view==='room')document.querySelector('#visibleCount').textContent=`${matching().filter(t=>unfinished(t,i)).length} visible matches · ${counts(scope())[i]} total pending · 3秒后恢复`;highlightTimer=setTimeout(release,3000);}function release(){clearHold();const count=document.querySelector('#visibleCount');if(count)count.textContent=`${matching().length} / ${scope().length} rows · 点击圆圈高亮3秒`;}
document.addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-drag]');if(handle)handle.closest('tr').classList.add('grip-down');});document.addEventListener('pointerup',clearDragFeedback);document.addEventListener('pointercancel',clearDragFeedback);window.addEventListener('blur',()=>{release();clearDragFeedback();});document.addEventListener('visibilitychange',release);document.addEventListener('keydown',e=>{const c=e.target.closest('[data-hold]');if(c&&[' ','Enter'].includes(e.key)){e.preventDefault();hold(Number(c.dataset.hold));}});
function clearDragFeedback(){document.querySelectorAll('.grip-down,.dragging-row,.drop-target').forEach(r=>r.classList.remove('grip-down','dragging-row','drop-target'));}
function waitingTip(id,anchor){document.querySelector('#waitingTip')?.remove();const t=find(id),i=next(t),s=stages[i];if(!s)return pathDialog(id);const tip=document.createElement('div');tip.id='waitingTip';tip.className='waiting-tip';tip.setAttribute('role','status');tip.innerHTML=`<b>${i===0?'此行订单正在等待Purchaser输入P.O.号码。':`此行订单正在等待${s[4]}${s[3]}。`}</b><span>${i===0?'This task is waiting for the Purchaser to enter a supplier P.O. number.':`${s[4]}: ${s[2]}.`}</span>${i===4?`<button class="btn primary" data-action="${t.id}">Noted</button>`:''}`;document.body.append(tip);const r=anchor.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(r.left,innerWidth-tip.offsetWidth-8))+'px';tip.style.top=Math.min(r.bottom+5,innerHeight-tip.offsetHeight-8)+'px';}
document.addEventListener('click',e=>{if(!e.target.closest('#waitingTip'))document.querySelector('#waitingTip')?.remove();const poInput=e.target.closest('input[data-po]');if(poInput)return openPo(poInput.dataset.po);const b=e.target.closest('button');if(!b)return;if(b.dataset.hold)return hold(Number(b.dataset.hold));if(b.dataset.waiting)return waitingTip(b.dataset.waiting,b);if(b.dataset.view)return navigate(b.dataset.view);if(b.dataset.customer)return navigate('room',b.dataset.customer);if(b.dataset.po)return openPo(b.dataset.po);if(b.dataset.path)return pathDialog(b.dataset.path);if(b.dataset.risk)return riskDialog(b.dataset.risk);if(b.dataset.action)return actionDialog(b.dataset.action);if(b.dataset.qty)return qtyDialog(b.dataset.qty);if(b.dataset.receipt)return receiptDialog(b.dataset.receipt);if(b.dataset.poDetails){const rows=active().filter(t=>t.po===b.dataset.poDetails);return openDialog('Supplier P.O. '+esc(b.dataset.poDetails),`${rows.length} independent tasks`,listRows(rows));}if(b.dataset.payment){const p=db.paymentRequests.find(p=>p.id===b.dataset.payment);return openDialog(p.id,'Account操作 · Purchase只读',`<div class="stats"><div><span>Requested</span><b>${p.amount}</b></div><div><span>Paid</span><b>${p.paid}</b></div><div><span>Balance</span><b>${p.amount-p.paid}</b></div></div><div class="note">${esc(p.reason)||'普通付款申请'}<br>同P.O.的每次申请独立，部分付款不代表全部付清。</div>`);}switch(b.id){case'clearSelection':selected.clear();renderRoom();break;case'riskFilter':riskSummary();break;case'moveSelected':moveDialog();break;case'saveOrder':{for(const t of scope())if(sequenceDraft?.indexOf(t.id)!==t.seq)event(t,'Row Position Updated','Purchase排列已保存 · ID/数量/P.O.保留');const movedSequence=scope().map(t=>t.id),previousSequence=sequenceDraft;sequenceDraft=null;if(!persist()){sequenceDraft=previousSequence;movedSequence.forEach((id,i)=>find(id).seq=i);return;}renderRoom();toast('示例排列已保存；真实其它部门未连接。');break;}case'cancelOrder':if(sequenceDraft)sequenceDraft.forEach((id,i)=>find(id).seq=i);sequenceDraft=null;renderRoom();break;case'saveEdits':if(drafts.size)savePrices();if(!drafts.size&&sequenceDraft)document.querySelector('#saveOrder').click();break;case'savePrices':savePrices();break;case'cancelPrices':drafts.clear();renderRoom();break;case'reset':openDialog('Reset demo / 重置示例','只重置本地示例',`<p>清除本浏览器中的演示编辑，回到初始30任务／5条已登记P.O.。</p>`,'<button class="btn primary" id="dialogSave">Reset</button>',()=>{db=seed();drafts.clear();selected.clear();sequenceDraft=null;if(!persist())return;closeDialog();render();toast('示例已重置。');});break;}});
document.addEventListener('change',e=>{const el=e.target;if(el.classList.contains('rowcheck')){el.checked?selected.add(el.dataset.id):selected.delete(el.dataset.id);el.closest('tr').classList.toggle('selected',el.checked);document.querySelector('#selectedLabel').textContent=`${selected.size} selected / 已选`;return;}if(el.id==='selectVisible'){matching().forEach(t=>el.checked?selected.add(t.id):selected.delete(t.id));renderRoom();return;}if(el.dataset.supplier){draft(el.dataset.supplier).supplier=el.value;document.querySelector('#savePrices').disabled=false;document.querySelector('#cancelPrices').disabled=false;document.querySelector('#saveEdits').disabled=false;return;}const ids={supplierFilter:'supplier',orderFilter:'order',stageFilter:'stage'};if(ids[el.id]){filter[ids[el.id]]=el.value;renderRoom();}});
document.addEventListener('input',e=>{const el=e.target;if(modal.open&&content.contains(el)){const message=content.querySelector('#dialogError');if(message)message.textContent='';}if(el.dataset.price){const d=draft(el.dataset.price),field=Number(el.dataset.field);d.price[field]=el.value;if(field===0)d.priceBasis=el.value.trim()?'pc':'ctn';if(field===1)d.priceBasis='ctn';el.classList.toggle('invalid',!(Number(el.dataset.field)===0&&!el.value.trim())&&!validatePrice(el.value,Number(el.dataset.field)));refreshCost(el.dataset.price);document.querySelector('#savePrices').disabled=false;document.querySelector('#cancelPrices').disabled=false;document.querySelector('#saveEdits').disabled=false;}if(el.id==='search'){filter.query=el.value;release();document.querySelector('#taskRows').innerHTML=rowMarkup(matching());fitItemNames();document.querySelector('#visibleCount').textContent=`${matching().length} / ${scope().length} rows`; }if(el.id==='customerSearch')app.querySelectorAll('tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(el.value.toLowerCase()));});
document.addEventListener('focusout',e=>{const el=e.target;if(el.matches('[data-hold]'))release();if(el.dataset.price&&!el.readOnly&&drafts.has(el.dataset.price)&&validatePrice(el.value,Number(el.dataset.field))){const v=formatPrice(el.value,Number(el.dataset.field));el.value=v;draft(el.dataset.price).price[Number(el.dataset.field)]=v;refreshCost(el.dataset.price);}});
document.addEventListener('dragstart',e=>{const h=e.target.closest('[data-drag]');if(!h)return;dragId=h.dataset.drag;h.closest('tr').classList.add('dragging-row');e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';});document.addEventListener('dragover',e=>{if(dragId&&e.target.closest('tr[data-id]')){e.preventDefault();document.querySelectorAll('.drop-target').forEach(r=>r.classList.remove('drop-target'));e.target.closest('tr').classList.add('drop-target');}});document.addEventListener('drop',e=>{const target=e.target.closest('tr[data-id]');if(!target||!dragId)return;e.preventDefault();if(dragId===target.dataset.id){dragId=null;return;}if(!sequenceDraft)sequenceDraft=scope().map(t=>t.id);const ids=scope().map(t=>t.id);const from=ids.indexOf(dragId),to=ids.indexOf(target.dataset.id);if(from>=0&&to>=0){ids.splice(from,1);ids.splice(ids.indexOf(target.dataset.id),0,dragId);ids.forEach((id,i)=>find(id).seq=i);}dragId=null;clearDragFeedback();renderRoom();toast('行已移动，请点击Save保存。');});document.addEventListener('dragend',()=>{dragId=null;clearDragFeedback();});
modal.addEventListener('cancel',()=>{content.innerHTML='';});modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});window.addEventListener('beforeunload',e=>{if(drafts.size||sequenceDraft){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{const el=e.target;if(!el.dataset.price||e.isComposing||!['Enter','ArrowUp','ArrowDown'].includes(e.key))return;const fields=[...document.querySelectorAll('#taskRows [data-price]')],index=fields.indexOf(el),offset=e.key==='Enter'?(e.shiftKey?-1:1):e.key==='ArrowUp'?-5:5,target=fields[index+offset];e.preventDefault();if(target){target.focus();target.select();}});
window.addEventListener('resize',fitItemNames);persist();render();
