/* Independent UX candidate. Company and supplier examples are fictional. */
const ORIGINAL_STORAGE='fmcg-purchase-ux-demo-20261008-v1';
const COMPANY_SELECTION=ORIGINAL_STORAGE+':company';
const SHARED_SUPPLIERS=ORIGINAL_STORAGE+':shared-suppliers:v1';
let companyCode='NCT';
try{if(localStorage.getItem(COMPANY_SELECTION)==='GHR')companyCode='GHR';}catch{}
function companyStorage(code){return code==='NCT'?ORIGINAL_STORAGE:ORIGINAL_STORAGE+':GHR';}
function companyName(){return companyCode==='NCT'?'North Cape Trading':'Global HR';}
function seedCompany(){const data=seed();if(companyCode==='NCT')return data;data.tasks=data.tasks.slice(0,6).map((t,i)=>({...t,id:'T-GHR-'+String(i+1).padStart(4,'0'),orderId:'O-GHR-DEMO-001',customerId:'DEMO-ALPHA',po:'',seq:i,done:Array(9).fill(false),history:[{kind:'Order received',at:t.receivedAt,by:'Law',detail:'GHR独立示例任务'}]}));data.paymentRequests=[];return data;}
const SUPPLIER_FIXTURES=['A','B','C','D','E','F'].map((letter,i)=>({id:'Supplier '+letter,name:'Supplier '+letter+' Trading & Distribution Sdn. Bhd.',registration:'',address:'',phone:'',email:'',website:'',brands:['Demo Brand '+String(i+1).padStart(2,'0')],contacts:[]}));
let sharedSuppliers=structuredClone(SUPPLIER_FIXTURES),supplierFormOpen=false,supplierQuery='';
try{const data=JSON.parse(localStorage.getItem(SHARED_SUPPLIERS));if(Array.isArray(data)&&data.every(s=>s.id&&s.name&&Array.isArray(s.brands)&&Array.isArray(s.contacts)))sharedSuppliers=data;}catch{}
function supplierName(id){return sharedSuppliers.find(s=>s.id===id)?.name||id;}
function taskBrand(t){return t.brand||'Demo Brand '+String(Math.max(0,products.findIndex(p=>p[0]===t.barcode))%6+1).padStart(2,'0');}
function rankedSuppliers(t){const match=s=>s.brands.some(b=>b.toLowerCase()===taskBrand(t).toLowerCase());return [...sharedSuppliers].sort((a,b)=>Number(match(b))-Number(match(a))||a.name.localeCompare(b.name));}
function supplierOptions(t){const options=rankedSuppliers(t);if(!options.some(s=>s.id===supplier(t)))options.push({id:supplier(t),name:supplierName(supplier(t)),brands:[]});return options.map(s=>`<option value="${esc(s.id)}" ${supplier(t)===s.id?'selected':''}>${esc(s.name)}${s.brands.some(b=>b.toLowerCase()===taskBrand(t).toLowerCase())?' · Brand match':''}</option>`).join('');}
function supplierTasks(id){return [...new Map(active().filter(t=>t.supplier===id).map(t=>[t.id,t])).values()];}
function entryIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13 4h7v16h-7M3 12h13m-4-4 4 4-4 4"/></svg>';}
function updateCompanyHeader(){document.querySelector('#companySelect').value=companyCode;document.querySelector('#workspaceCompany').textContent=companyCode;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view||(view==='room'&&b.dataset.view==='dashboard')));}
function switchCompany(code){if(!['NCT','GHR'].includes(code)||code===companyCode)return;
 if(drafts.size||sequenceDraft||formDraft||recoveryConflict||draftCacheFailure||modal.open){document.querySelector('#companySelect').value=companyCode;toast('请先保存或处理当前草稿，再切换公司。');return;}
 let nextDb;try{const raw=localStorage.getItem(companyStorage(code));if(raw){nextDb=JSON.parse(raw);if(!nextDb?.customers||!nextDb?.tasks||!nextDb?.paymentRequests)throw Error('invalid');}localStorage.setItem(COMPANY_SELECTION,code);}catch{document.querySelector('#companySelect').value=companyCode;return toast('无法读取公司工作区，当前工作已保留。');}
 companyCode=code;STORAGE=companyStorage(code);DRAFT_STORAGE=STORAGE+':draft:Law:Purchase:v1';db=nextDb||seedCompany();lastSaved=structuredClone(db);
 for(const t of db.tasks)if(t.ea===undefined){t.ea=DEMO_EA[products.findIndex(p=>p[0]===t.barcode)];t.eaSource='DEMO';}
 customerId=db.customers[0]?.id;selected.clear();filter={query:'',supplier:'',order:'',stage:'',risk:false};view='dashboard';drafts.clear();sequenceDraft=null;formContext=null;formDraft=null;recoveryConflict=null;restoredDraft=false;draftCacheFailure='';
 restoreDraftCache();render();restoreFormDraft();updateSaveNotice();
}
function dashboardCustomerTable(){return `<table class="directory customer-directory"><colgroup><col style="width:34%"><col style="width:30%"><col style="width:12%"><col style="width:12%"><col style="width:12%"></colgroup><thead><tr><th>Customer</th><th>Est. Shipment Date</th><th>Tasks</th><th>Risk</th><th>Entry</th></tr></thead><tbody>${db.customers.map(c=>{const rows=active().filter(t=>t.customerId===c.id),risk=rows.filter(t=>t.risk||projectedGp(t)<0).length;return `<tr data-customer-name="${esc(c.name.toLowerCase())}"><td><button class="customerlink" data-customer="${esc(c.id)}">${esc(c.name)}</button></td><td>${rows.length?shipmentSummary(rows):'—'}</td><td><b class="task-total">${rows.length}</b></td><td>${risk?`<span class="risk-count">${risk}</span>`:'—'}</td><td><button class="room-entry" data-customer="${esc(c.id)}" aria-label="Open ${esc(c.name)} Purchase Room">${entryIcon()}</button></td></tr>`;}).join('')}</tbody></table>`;}
function supplierTable(){return `<table class="directory supplier-directory"><colgroup><col style="width:48%"><col style="width:29%"><col style="width:12%"><col style="width:11%"></colgroup><thead><tr><th>Supplier</th><th>Brands</th><th>Tasks</th><th>Profile</th></tr></thead><tbody>${sharedSuppliers.map(s=>`<tr data-supplier-name="${esc((s.name+' '+s.brands.join(' ')).toLowerCase())}"><td><button class="supplier-name" data-profile="${esc(s.id)}">${esc(s.name)}</button></td><td><span class="brand-preview">${s.brands[0]?`<span class="brand-chip">${esc(s.brands[0])}</span>`:'—'}${s.brands.length>1?`<button data-profile="${esc(s.id)}" aria-label="View all ${s.brands.length} brands">+${s.brands.length-1}</button>`:''}</span></td><td><button class="task-count" data-supplier-tasks="${esc(s.id)}" aria-label="${esc(s.name)} ${companyCode} tasks">${supplierTasks(s.id).length}</button></td><td><button class="profile-entry" data-profile="${esc(s.id)}" aria-label="View ${esc(s.name)} profile">${entryIcon()}</button></td></tr>`).join('')}</tbody></table>`;}
function renderDashboard(){app.innerHTML=heading('Purchase Dashboard',`${companyCode} · ${companyName()}`)+metrics(active())+`<div class="dashboard-grid"><section class="panel"><div class="panelhead"><div><h2>Customers</h2><span class="muted">${companyCode} 客户任务</span></div><b class="panel-total">${db.customers.length}</b></div><div class="directory-tools"><input id="dashboardCustomerSearch" placeholder="Search customer" aria-label="Search customer"></div><div class="directory-scroll" aria-label="Customer directory">${dashboardCustomerTable()}</div></section><section class="panel"><div class="panelhead"><div><h2>Suppliers <span class="shared-label">Shared</span></h2><span class="muted">共用资料 · 数量仅统计 ${companyCode} 任务</span></div><button class="btn primary" id="addSupplier">＋ Add Supplier</button></div><div class="directory-tools"><input id="supplierSearch" placeholder="Search supplier / brand" aria-label="Search supplier or brand"></div><div class="directory-scroll" aria-label="Supplier directory">${supplierTable()}</div></section></div>`;}
function supplierTaskDialog(id){const rows=supplierTasks(id),groups=new Map();for(const t of rows){if(!groups.has(t.customerId))groups.set(t.customerId,[]);groups.get(t.customerId).push(t);}openDialog('Supplier Tasks',`${companyCode} · ${supplierName(id)}`,rows.length?[...groups].map(([cid,tasks])=>`<section class="supplier-task-group"><h3>${esc(db.customers.find(c=>c.id===cid)?.name||cid)} <button class="room-entry" data-supplier-room="${esc(cid)}" data-room-supplier="${esc(id)}" aria-label="Open related Purchase Room">${entryIcon()}</button></h3><table class="rowlist"><thead><tr><th>Product</th><th>Qty</th><th>P.O.</th></tr></thead><tbody>${tasks.map(t=>`<tr><td><b>${esc(t.name)}</b><small>${esc(t.barcode)} · ${esc(t.packing)}</small></td><td>${t.ord}</td><td>${esc(t.po)||'—'}</td></tr>`).join('')}</tbody></table></section>`).join(''):'<div class="note">当前公司没有关联的活动采购任务。</div>');}
function profileDialog(id){const s=sharedSuppliers.find(s=>s.id===id);if(!s)return;openDialog('Supplier Profile',`${companyCode} · 供应商资料由 NCT / GHR 共用`, `<div class="supplier-profile"><h3>${esc(s.name)}</h3><div class="profile-details">${[['Registration',s.registration],['Address',s.address],['Phone',s.phone],['Email',s.email],['Website',s.website]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)||'—'}</b></div>`).join('')}</div><h3>Brands</h3><p>${s.brands.map(b=>`<span class="brand-chip">${esc(b)}</span>`).join('')||'—'}</p><h3>Sales Contacts</h3>${s.contacts.length?s.contacts.map(c=>`<p><b>${esc(c.name)}</b> · ${esc(c.role)}<br>${esc(c.phone)} · ${esc(c.email)}</p>`).join(''):'<p class="muted">尚未登记销售员</p>'}<button class="task-count" data-supplier-tasks="${esc(id)}">${companyCode} Tasks ${supplierTasks(id).length}</button></div>`);content.querySelector('.dialogfoot .actions').insertAdjacentHTML('beforeend',`<button class="btn primary" data-edit-supplier="${esc(id)}">Edit Profile</button>`);}
function supplierEditor(id){const existing=sharedSuppliers.find(s=>s.id===id),s=existing||{name:'',registration:'',address:'',phone:'',email:'',website:'',brands:[],contacts:[]};supplierFormOpen=true;
 openDialog(existing?'Edit Supplier':'Add Supplier','Shared · NCT / GHR 共用供应商资料',`<div class="supplier-form"><div class="field full"><label for="supplierName">Company Name *</label><input id="supplierName" maxlength="160" value="${esc(s.name)}"></div>${[['Registration','supplierRegistration',s.registration],['Phone','supplierPhone',s.phone],['Email','supplierEmail',s.email],['Website','supplierWebsite',s.website]].map(([k,key,v])=>`<div class="field"><label for="${key}">${k}</label><input id="${key}" value="${esc(v)}" maxlength="200"></div>`).join('')}<div class="field full"><label for="supplierAddress">Address</label><textarea id="supplierAddress" maxlength="500">${esc(s.address)}</textarea></div><div class="field full"><label for="supplierBrands">Brands · 每行一个品牌</label><textarea id="supplierBrands" maxlength="2000" placeholder="品牌名称">${esc(s.brands.join('\n'))}</textarea></div><div class="full"><h3>Sales Contacts</h3><div id="supplierContacts"></div><button class="btn" id="addSupplierContact">＋ Add Contact</button></div></div>`,'<button class="btn primary" id="dialogSave">Save</button>',()=>{
  const value=key=>content.querySelector('#'+key).value.trim(),name=value('supplierName');if(!name)return error('请填写供应商公司名称。');if(sharedSuppliers.some(x=>x.id!==id&&x.name.trim().toLowerCase()===name.toLowerCase()))return error('此供应商已存在，请编辑现有资料。');
  const contacts=[...content.querySelectorAll('.contact-row')].map(row=>Object.fromEntries([...row.querySelectorAll('input')].map(el=>[el.dataset.contactField,el.value.trim()]))).filter(c=>Object.values(c).some(Boolean));if(contacts.some(c=>!c.name))return error('请填写销售员姓名。');
  const added={...s,id:existing?.id||'SUP-'+crypto.randomUUID(),name,registration:value('supplierRegistration'),phone:value('supplierPhone'),email:value('supplierEmail'),website:value('supplierWebsite'),address:value('supplierAddress'),brands:[...new Set(value('supplierBrands').split('\n').map(b=>b.trim()).filter(Boolean))],contacts,updatedAt:now(),updatedBy:'Law (demo)'};
  const nextSuppliers=existing?sharedSuppliers.map(x=>x.id===id?added:x):[...sharedSuppliers,added];try{localStorage.setItem(SHARED_SUPPLIERS,JSON.stringify(nextSuppliers));}catch{return error('保存失败，输入仍保留，请重试。');}sharedSuppliers=nextSuppliers;supplierFormOpen=false;closeDialog();render();toast('供应商示例已保存，NCT / GHR 共用。');
 });modal.classList.add('supplier-dialog');
 function addContact(c={}){content.querySelector('#supplierContacts').insertAdjacentHTML('beforeend',`<div class="contact-row">${[['name','Name *'],['role','Role'],['phone','Phone'],['email','Email']].map(([k,label])=>`<label>${label}<input data-contact-field="${k}" value="${esc(c[k]||'')}" maxlength="160"></label>`).join('')}</div>`);}
 (s.contacts.length?s.contacts:[{}]).forEach(addContact);content.querySelector('#addSupplierContact').onclick=()=>addContact();
 const cancel=()=>{supplierFormOpen=false;closeDialog();};content.querySelector('#cancelDialog').onclick=cancel;content.querySelector('#closeDialog').onclick=cancel;
}
document.addEventListener('change',e=>{if(e.target.id==='companySelect')switchCompany(e.target.value);});
document.addEventListener('input',e=>{if(e.target.id==='supplierSearch'){supplierQuery=e.target.value.toLowerCase();app.querySelectorAll('[data-supplier-name]').forEach(r=>r.hidden=!r.dataset.supplierName.includes(supplierQuery));}if(e.target.id==='dashboardCustomerSearch')app.querySelectorAll('[data-customer-name]').forEach(r=>r.hidden=!r.dataset.customerName.includes(e.target.value.toLowerCase()));});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='addSupplier'){supplierEditor();return;}if(b.dataset.profile){profileDialog(b.dataset.profile);return;}if(b.dataset.editSupplier){closeDialog();supplierEditor(b.dataset.editSupplier);return;}if(b.dataset.supplierTasks){if(modal.open)closeDialog();supplierTaskDialog(b.dataset.supplierTasks);return;}if(b.dataset.supplierRoom){closeDialog();navigate('room',b.dataset.supplierRoom);filter.supplier=b.dataset.roomSupplier;renderRoom();}});

