/* Independent UX candidate. Company and supplier examples are fictional. */
const ORIGINAL_STORAGE='fmcg-purchase-ux-demo-20261008-v1';
const COMPANY_SELECTION=ORIGINAL_STORAGE+':company';
const SHARED_SUPPLIERS=ORIGINAL_STORAGE+':shared-suppliers:v1';
let companyCode='NCT';
try{if(localStorage.getItem(COMPANY_SELECTION)==='GHR')companyCode='GHR';}catch{}
function companyStorage(code){return code==='NCT'?ORIGINAL_STORAGE:ORIGINAL_STORAGE+':GHR';}
function companyName(){return companyCode==='NCT'?'North Cape Trading':'Global HR';}
function seedCompany(){const data=seed();if(companyCode==='NCT')return data;data.tasks=data.tasks.slice(0,6).map((t,i)=>({...t,id:'T-GHR-'+String(i+1).padStart(4,'0'),orderId:'O-GHR-DEMO-001',customerId:'DEMO-ALPHA',po:'',seq:i,done:Array(9).fill(false),history:[{kind:'Order received',at:t.receivedAt,by:'Law',detail:'GHR独立示例任务'}]}));data.paymentRequests=[];return data;}
const SUPPLIER_FIXTURES=['A','B','C','D','E','F'].map((letter,i)=>({id:'Supplier '+letter,shortName:'SUPPLIER '+letter,name:'Supplier '+letter+' Trading & Distribution Sdn. Bhd.',registration:'',address:'',phone:'',email:'',website:'',brands:['Demo Brand '+String(i+1).padStart(2,'0')],contacts:[]}));
let sharedSuppliers=structuredClone(SUPPLIER_FIXTURES),supplierFormOpen=false,supplierQuery='';
try{const data=JSON.parse(localStorage.getItem(SHARED_SUPPLIERS));if(Array.isArray(data)&&data.every(s=>s.id&&s.name&&Array.isArray(s.brands)&&Array.isArray(s.contacts)))sharedSuppliers=data;}catch{}
function supplierName(id){return sharedSuppliers.find(s=>s.id===id)?.name||id;}
function supplierShortName(id){const s=sharedSuppliers.find(s=>s.id===id);return s?.shortName?.trim()||s?.name||id;}
function supplierEditIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="6" r="4"/><path d="M12 13a8 8 0 0 0-11 7v2h10m4-6 5-5 3 3-5 5-4 1zM19 12l3 3"/></svg>';}
const CONTACT_ROLES=['Sales Representative','Sales Manager','Director','Account Dept.','Warehouse','Others'];
function contactRoleOptions(role=''){const value=normalizeSupplierValue('role',role),known=CONTACT_ROLES.map(label=>({value:label.toUpperCase(),label}));if(value&&!known.some(r=>r.value===value))known.unshift({value,label:role});return '<option value="">Select Role</option>'+known.map(r=>`<option value="${esc(r.value)}" ${r.value===value?'selected':''}>${esc(r.label)}</option>`).join('');}
function taskBrand(t){return t.brand||'Demo Brand '+String(Math.max(0,products.findIndex(p=>p[0]===t.barcode))%6+1).padStart(2,'0');}
function rankedSuppliers(t){const match=s=>s.brands.some(b=>b.toLowerCase()===taskBrand(t).toLowerCase());return [...sharedSuppliers].sort((a,b)=>Number(match(b))-Number(match(a))||a.name.localeCompare(b.name));}
function supplierOptions(t){const options=rankedSuppliers(t);if(!options.some(s=>s.id===supplier(t)))options.push({id:supplier(t),name:supplierName(supplier(t)),brands:[]});return options.map(s=>`<option value="${esc(s.id)}" ${supplier(t)===s.id?'selected':''}>${esc(s.shortName?.trim()||s.name)}</option>`).join('');}
function isRiskTask(t){const gp=projectedGp(t);return Boolean(t.risk)||(gp!==null&&gp<0);}
function supplierRiskTasks(id){return supplierTasks(id).filter(isRiskTask);}
function normalizeSupplierValue(key,value){const text=String(value??'').trim();return ['supplierEmail','supplierWebsite','email'].includes(key)?text:text.toUpperCase();}
function uppercaseSupplierInput(el){if(el.type==='checkbox'||el.id==='supplierEmail'||el.id==='supplierWebsite'||el.dataset.contactField==='email')return;const raw=el.value,start=el.selectionStart,end=el.selectionEnd;el.value=raw.toUpperCase();if(typeof start==='number')el.setSelectionRange(raw.slice(0,start).toUpperCase().length,raw.slice(0,end).toUpperCase().length);}
function supplierTasks(id){return [...new Map(active().filter(t=>t.supplier===id).map(t=>[t.id,t])).values()];}
function entryIcon(){return '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M13 4h7v16h-7M3 12h13m-4-4 4 4-4 4"/></svg>';}
function updateCompanyHeader(){document.querySelector('#companySelect').value=companyCode;document.querySelector('#workspaceCompany').textContent=companyCode;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view||(view==='room'&&b.dataset.view==='dashboard')));}
function switchCompany(code){if(!['NCT','GHR'].includes(code)||code===companyCode)return;
 if(drafts.size||sequenceDraft||formDraft||recoveryConflict||draftCacheFailure||modal.open){document.querySelector('#companySelect').value=companyCode;toast('请先保存或处理当前草稿，再切换公司。');return;}
 let nextDb;try{const raw=localStorage.getItem(companyStorage(code));if(raw){nextDb=JSON.parse(raw);if(!nextDb?.customers||!nextDb?.tasks||!nextDb?.paymentRequests)throw Error('invalid');}localStorage.setItem(COMPANY_SELECTION,code);}catch{document.querySelector('#companySelect').value=companyCode;return toast('无法读取公司工作区，当前工作已保留。');}
 companyCode=code;STORAGE=companyStorage(code);DRAFT_STORAGE=STORAGE+':draft:Law:Purchase:v1';db=nextDb||seedCompany();lastSaved=structuredClone(db);
 for(const t of db.tasks)if(t.ea===undefined){t.ea=DEMO_EA[products.findIndex(p=>p[0]===t.barcode)];t.eaSource='DEMO';}
 customerId=db.customers[0]?.id;selected.clear();filter={query:'',supplier:'',order:'',stage:'',risk:false};view='dashboard';drafts.clear();sequenceDraft=null;formContext=null;formDraft=null;recoveryConflict=null;restoredDraft=false;draftCacheFailure='';
 restoreDraftCache();render();restoreFormDraft();updateSaveNotice();
}
function dashboardCustomerTable(){return `<table class="directory customer-directory"><colgroup><col style="width:34%"><col style="width:30%"><col style="width:12%"><col style="width:12%"><col style="width:12%"></colgroup><thead><tr><th>Customer</th><th>Est. Shipment Date</th><th>Tasks</th><th>Risk</th><th>Entry</th></tr></thead><tbody>${db.customers.map(c=>{const rows=active().filter(t=>t.customerId===c.id),risk=rows.filter(isRiskTask).length;return `<tr data-customer-name="${esc(c.name.toLowerCase())}"><td><button class="customerlink" data-customer="${esc(c.id)}">${esc(c.name)}</button></td><td>${rows.length?shipmentSummary(rows):'—'}</td><td class="numeric"><b class="task-total">${rows.length}</b></td><td class="numeric">${risk?`<span class="risk-count">${risk}</span>`:'<span class="zero-risk">—</span>'}</td><td><button class="room-entry" data-customer="${esc(c.id)}" aria-label="Open ${esc(c.name)} Purchase Room">${entryIcon()}</button></td></tr>`;}).join('')}</tbody></table>`;}
function supplierTable(){return `<table class="directory supplier-directory"><colgroup><col style="width:56%"><col style="width:14%"><col style="width:14%"><col style="width:16%"></colgroup><thead><tr><th>Supplier</th><th>Tasks</th><th>Risk</th><th>Edit</th></tr></thead><tbody>${sharedSuppliers.map(s=>{const risk=supplierRiskTasks(s.id).length;return `<tr data-supplier-name="${esc((s.name+' '+s.brands.join(' ')).toLowerCase())}"><td><button class="supplier-name" data-profile="${esc(s.id)}">${esc(s.name)}</button></td><td class="numeric"><button class="task-count" data-supplier-tasks="${esc(s.id)}" aria-label="${esc(s.name)} ${companyCode} tasks">${supplierTasks(s.id).length}</button></td><td class="numeric">${risk?`<button class="supplier-risk-count" data-supplier-risk="${esc(s.id)}" aria-label="${esc(s.name)} ${companyCode} risk tasks">${risk}</button>`:'<span class="zero-risk">—</span>'}</td><td class="action-cell"><button class="supplier-edit" data-edit-supplier="${esc(s.id)}" aria-label="Edit ${esc(s.name)}">${supplierEditIcon()}</button></td></tr>`;}).join('')}</tbody></table>`;}
function dashboardIcon(kind){const shapes={orders:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6M9 16h6"/>',tasks:'<path d="m3 6 2 2 3-4M11 6h10m-18 8 2 2 3-4M11 14h10M11 21h10"/>',payments:'<text x="12" y="20" text-anchor="middle" fill="currentColor" stroke="none" font-family="Arial,sans-serif" font-size="23" font-weight="600">$</text>',risk:'<path d="m12 3 10 18H2zM12 9v5m0 3v1"/>',customers:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m2-16a3 3 0 0 1 0 6m1 3a5 5 0 0 1 3 5v2"/>',suppliers:'<path d="M3 21h18M5 21V6l7-3v18m0-12h7v12M8 8v2m0 3v2m8-2v2m0 3v1"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${shapes[kind]||''}</svg>`;}
function dashboardSummary(){const rows=active(),values=[['orders','Active Orders',new Set(rows.map(t=>t.orderId)).size],['tasks','Purchase Tasks',rows.length],['payments','Payment Requests',db.paymentRequests.filter(p=>p.paid<p.amount).length],['risk','At Risk',rows.filter(isRiskTask).length]];return `<section class="dashboard-summary" aria-label="Company workload">${values.map(([key,label,n])=>`<div class="summary-item ${key==='risk'?'summary-risk':''}"><span class="summary-icon">${dashboardIcon(key)}</span><div><span class="summary-label">${label}</span><b>${n}</b></div></div>`).join('')}</section>`;}
function renderDashboard(){app.innerHTML=`<div class="dashboard-title"><h1>Purchase Dashboard</h1><span class="dashboard-company-tag">${companyCode} · ${companyName()}</span></div>`+dashboardSummary()+`<div class="dashboard-grid"><section class="panel"><div class="panelhead"><div class="directory-heading"><span class="directory-icon">${dashboardIcon('customers')}</span><div><h2>Customers</h2><span class="muted">${companyCode} customer workspace</span></div></div><span class="directory-total">${db.customers.length}</span></div><div class="directory-tools"><input id="dashboardCustomerSearch" placeholder="Search customer" aria-label="Search customer"></div><div class="directory-scroll" aria-label="Customer directory">${dashboardCustomerTable()}</div><div class="directory-footer"><span id="customerResultCount">${db.customers.length} customers</span><span>Open room to manage tasks</span></div></section><section class="panel"><div class="panelhead"><div class="directory-heading"><span class="directory-icon">${dashboardIcon('suppliers')}</span><div><h2>Suppliers <span class="shared-label">Shared</span></h2><span class="muted">Task counts for ${companyCode}</span></div></div><button class="btn primary" id="addSupplier">＋ Add Supplier</button></div><div class="directory-tools"><input id="supplierSearch" placeholder="Search supplier / brand" aria-label="Search supplier or brand"></div><div class="directory-scroll" aria-label="Supplier directory">${supplierTable()}</div><div class="directory-footer"><span id="supplierResultCount">${sharedSuppliers.length} suppliers</span><span>Shared by NCT / GHR</span></div></section></div>`;}
function supplierTaskDialog(id,riskOnly=false){const rows=riskOnly?supplierRiskTasks(id):supplierTasks(id),groups=new Map();for(const t of rows){if(!groups.has(t.customerId))groups.set(t.customerId,[]);groups.get(t.customerId).push(t);}openDialog(riskOnly?'Supplier Risk':'Supplier Tasks',`${supplierName(id)}`,rows.length?[...groups].map(([cid,tasks])=>`<section class="supplier-task-group"><h3>${esc(db.customers.find(c=>c.id===cid)?.name||cid)} <button class="room-entry" data-supplier-room="${esc(cid)}" data-room-supplier="${esc(id)}" aria-label="Open related Purchase Room">${entryIcon()}</button></h3><table class="rowlist"><thead><tr><th>Product</th><th>Qty</th><th>P.O.</th>${riskOnly?'<th>Risk</th>':''}</tr></thead><tbody>${tasks.map(t=>`<tr><td><b>${esc(t.name)}</b><small>${esc(t.barcode)} · ${esc(t.packing)}</small></td><td>${t.ord}</td><td>${esc(t.po)||'—'}</td>${riskOnly?`<td class="risk-detail">${[t.risk?esc(t.risk.reason||'Receipt difference'):'',projectedGp(t)!==null&&projectedGp(t)<0?'Negative GP · '+gpMarkup(t):''].filter(Boolean).join('<br>')}</td>`:''}</tr>`).join('')}</tbody></table></section>`).join(''):'<div class="note">当前公司没有关联的活动采购任务。</div>');}
function profileDialog(id){const s=sharedSuppliers.find(s=>s.id===id);if(!s)return;openDialog('Supplier Profile',`${companyCode} · 供应商资料由 NCT / GHR 共用`, `<div class="supplier-profile"><h3>${esc(s.name)}</h3><div class="profile-details">${[['Short Name',s.shortName],['Registration',s.registration],['Address',s.address],['Phone',s.phone],['Email',s.email],['Website',s.website]].map(([k,v])=>`<div><span>${k}</span><b>${esc(v)||'—'}</b></div>`).join('')}</div><h3>Brands</h3><p>${s.brands.map(b=>`<span class="brand-chip">${esc(b)}</span>`).join('')||'—'}</p><h3>Sales Contacts</h3>${s.contacts.length?s.contacts.map(c=>`<p><b>${esc(c.name)}</b> · ${esc(c.role)}<br>${esc(c.phone)} · ${esc(c.email)}</p>`).join(''):'<p class="muted">尚未登记销售员</p>'}<button class="task-count" data-supplier-tasks="${esc(id)}">${companyCode} Tasks ${supplierTasks(id).length}</button></div>`);content.querySelector('.dialogfoot .actions').insertAdjacentHTML('beforeend',`<button class="btn primary" data-edit-supplier="${esc(id)}">Edit Profile</button>`);}
// Demo options only. Real POINTBASE brand authority is not connected here.
function brandOptions(existing=[]){return [...new Set([...Array.from({length:60},(_,i)=>'Demo Brand '+String(i+1).padStart(2,'0')),...sharedSuppliers.flatMap(s=>s.brands),...existing])].sort((a,b)=>a.localeCompare(b));}
function visibleBrands(options,selected,query,onlySelected){return options.filter(b=>b.toLowerCase().includes(query.trim().toLowerCase())&&(!onlySelected||selected.has(b)));}
function supplierEditor(id){const existing=sharedSuppliers.find(s=>s.id===id),s=existing||{name:'',shortName:'',registration:'',address:'',phone:'',email:'',website:'',brands:[],contacts:[]},selectedBrands=new Set(s.brands),options=brandOptions(s.brands);supplierFormOpen=true;
 openDialog(existing?'Edit Supplier':'Add Supplier','Shared · NCT / GHR 共用供应商资料',`
 <div class="supplier-tabs" role="tablist" aria-label="Supplier information"><button role="tab" id="supplier-tab-company" aria-controls="supplier-company-panel" aria-selected="true" data-supplier-tab="company">Company Info</button><button role="tab" id="supplier-tab-contacts" aria-controls="supplier-contacts-panel" aria-selected="false" data-supplier-tab="contacts">Sales Contacts</button><button role="tab" id="supplier-tab-brands" aria-controls="supplier-brands-panel" aria-selected="false" data-supplier-tab="brands">Brands <b id="brandTabCount">${selectedBrands.size}</b></button></div>
 <section id="supplier-company-panel" role="tabpanel" aria-labelledby="supplier-tab-company" data-supplier-panel="company"><div class="supplier-form"><div class="supplier-name-pair full"><div class="field"><label for="supplierName">Company Name *</label><input id="supplierName" maxlength="160" value="${esc(s.name)}"></div><div class="field"><label for="supplierShortName">Short Name</label><input id="supplierShortName" maxlength="40" value="${esc(s.shortName||'')}" placeholder="ABC TRADING"></div></div>${[['Registration','supplierRegistration',s.registration],['Phone','supplierPhone',s.phone],['Email','supplierEmail',s.email],['Website','supplierWebsite',s.website]].map(([k,key,v])=>`<div class="field"><label for="${key}">${k}</label><input id="${key}" value="${esc(v)}" maxlength="200"></div>`).join('')}<div class="field full"><label for="supplierAddress">Address</label><textarea id="supplierAddress" maxlength="500">${esc(s.address)}</textarea></div></div></section>
 <section id="supplier-contacts-panel" role="tabpanel" aria-labelledby="supplier-tab-contacts" data-supplier-panel="contacts" hidden><div id="supplierContacts"></div><button class="btn" id="addSupplierContact">＋ Add Contact</button></section>
 <section id="supplier-brands-panel" role="tabpanel" aria-labelledby="supplier-tab-brands" data-supplier-panel="brands" hidden><div class="brand-picker-tools"><input id="brandSearch" placeholder="Search brand" aria-label="Search brand"><label class="brand-selected-only"><input type="checkbox" id="selectedBrandsOnly"> Selected only</label></div><div class="brand-picker-summary"><b id="selectedBrandCount">${selectedBrands.size} selected</b><div><button class="btn" id="selectShownBrands">Select results</button><button class="btn" id="clearShownBrands">Clear results</button></div></div><div id="brandOptions" class="brand-options" aria-label="Brand choices"></div><p class="brand-source-note">示例品牌选项 · POINTBASE 品牌名单尚未接入。新品牌将统一在 POINTBASE 登记。</p></section>
 `,'<button class="btn primary" id="dialogSave">Save</button>',()=>{
  const value=key=>normalizeSupplierValue(key,content.querySelector('#'+key).value),name=value('supplierName');if(!name){showTab('company');return error('请填写供应商公司名称。');}if(sharedSuppliers.some(x=>x.id!==id&&x.name.trim().toLowerCase()===name.toLowerCase())){showTab('company');return error('此供应商已存在，请编辑现有资料。');}
  const contacts=[...content.querySelectorAll('.contact-row')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-contact-field]')].map(el=>[el.dataset.contactField,normalizeSupplierValue(el.dataset.contactField,el.value)]))).filter(c=>Object.values(c).some(Boolean));if(contacts.some(c=>!c.name)){showTab('contacts');return error('请填写销售员姓名。');}
  const added={...s,id:existing?.id||'SUP-'+crypto.randomUUID(),name,shortName:value('supplierShortName'),registration:value('supplierRegistration'),phone:value('supplierPhone'),email:value('supplierEmail'),website:value('supplierWebsite'),address:value('supplierAddress'),brands:[...selectedBrands].sort((a,b)=>a.localeCompare(b)),contacts,updatedAt:now(),updatedBy:'Law (demo)'};
  const nextSuppliers=existing?sharedSuppliers.map(x=>x.id===id?added:x):[...sharedSuppliers,added];try{localStorage.setItem(SHARED_SUPPLIERS,JSON.stringify(nextSuppliers));}catch{return error('保存失败，输入仍保留，请重试。');}sharedSuppliers=nextSuppliers;supplierFormOpen=false;closeDialog();render();toast('供应商示例已保存，NCT / GHR 共用。');
 });modal.classList.add('supplier-dialog');
 function showTab(key){content.querySelectorAll('[data-supplier-panel]').forEach(el=>el.hidden=el.dataset.supplierPanel!==key);content.querySelectorAll('[data-supplier-tab]').forEach(el=>{const on=el.dataset.supplierTab===key;el.setAttribute('aria-selected',String(on));el.tabIndex=on?0:-1;});}
 content.querySelectorAll('[data-supplier-tab]').forEach((b,i,buttons)=>{b.onclick=()=>showTab(b.dataset.supplierTab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].focus();showTab(buttons[next].dataset.supplierTab);}};});showTab('company');
 content.querySelectorAll('input:not([type=checkbox]),textarea').forEach(el=>{uppercaseSupplierInput(el);el.addEventListener('input',e=>{if(!e.isComposing)uppercaseSupplierInput(el);});el.addEventListener('compositionend',()=>uppercaseSupplierInput(el));});
 function addContact(c={}){content.querySelector('#supplierContacts').insertAdjacentHTML('beforeend',`<div class="contact-row">${[['name','Name *'],['role','Role'],['phone','Phone'],['email','Email']].map(([k,label])=>`<label>${label}${k==='role'?`<select data-contact-field="role" aria-label="Contact Role">${contactRoleOptions(c.role)}</select>`:`<input data-contact-field="${k}" value="${esc(c[k]||'')}" maxlength="160">`}</label>`).join('')}</div>`);}
 function normalizeContacts(){content.querySelectorAll('[data-contact-field]').forEach(el=>{uppercaseSupplierInput(el);if(!el.dataset.uppercaseBound){el.dataset.uppercaseBound='1';el.addEventListener('input',e=>{if(!e.isComposing)uppercaseSupplierInput(el);});el.addEventListener('compositionend',()=>uppercaseSupplierInput(el));}});}
 (s.contacts.length?s.contacts:[{}]).forEach(addContact);normalizeContacts();content.querySelector('#addSupplierContact').onclick=()=>{addContact();normalizeContacts();};
 function currentBrands(){return visibleBrands(options,selectedBrands,content.querySelector('#brandSearch').value,content.querySelector('#selectedBrandsOnly').checked);}
 function drawBrands(){const shown=currentBrands();content.querySelector('#selectedBrandCount').textContent=selectedBrands.size+' selected';content.querySelector('#brandTabCount').textContent=selectedBrands.size;content.querySelector('#brandOptions').innerHTML=shown.length?shown.map(b=>`<label class="brand-choice"><input type="checkbox" data-brand-choice="${esc(b)}" ${selectedBrands.has(b)?'checked':''}><span>${esc(b)}</span></label>`).join(''):'<div class="note">No matching brands</div>';content.querySelectorAll('[data-brand-choice]').forEach(el=>el.onchange=()=>{el.checked?selectedBrands.add(el.dataset.brandChoice):selectedBrands.delete(el.dataset.brandChoice);drawBrands();});}
 content.querySelector('#brandSearch').oninput=drawBrands;content.querySelector('#selectedBrandsOnly').onchange=drawBrands;content.querySelector('#selectShownBrands').onclick=()=>{currentBrands().forEach(b=>selectedBrands.add(b));drawBrands();};content.querySelector('#clearShownBrands').onclick=()=>{currentBrands().forEach(b=>selectedBrands.delete(b));drawBrands();};drawBrands();
 const cancel=()=>{supplierFormOpen=false;closeDialog();};content.querySelector('#cancelDialog').onclick=cancel;content.querySelector('#closeDialog').onclick=cancel;
}

document.addEventListener('change',e=>{if(e.target.id==='companySelect')switchCompany(e.target.value);});
document.addEventListener('input',e=>{if(e.target.id==='supplierSearch'){supplierQuery=e.target.value.toLowerCase();app.querySelectorAll('[data-supplier-name]').forEach(r=>r.hidden=!r.dataset.supplierName.includes(supplierQuery));const count=app.querySelector('#supplierResultCount');if(count)count.textContent=[...app.querySelectorAll('[data-supplier-name]')].filter(r=>!r.hidden).length+' / '+sharedSuppliers.length+' suppliers';}if(e.target.id==='dashboardCustomerSearch'){app.querySelectorAll('[data-customer-name]').forEach(r=>r.hidden=!r.dataset.customerName.includes(e.target.value.toLowerCase()));const count=app.querySelector('#customerResultCount');if(count)count.textContent=[...app.querySelectorAll('[data-customer-name]')].filter(r=>!r.hidden).length+' / '+db.customers.length+' customers';}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='addSupplier'){supplierEditor();return;}if(b.dataset.supplierRisk){if(modal.open)closeDialog();supplierTaskDialog(b.dataset.supplierRisk,true);return;}if(b.dataset.profile){profileDialog(b.dataset.profile);return;}if(b.dataset.editSupplier){closeDialog();supplierEditor(b.dataset.editSupplier);return;}if(b.dataset.supplierTasks){if(modal.open)closeDialog();supplierTaskDialog(b.dataset.supplierTasks);return;}if(b.dataset.supplierRoom){closeDialog();navigate('room',b.dataset.supplierRoom);filter.supplier=b.dataset.roomSupplier;renderRoom();}});



// Search filters rendered records only; stored payment and audit data stay intact.
document.addEventListener('input',e=>{if(e.target.id!=='ledgerSearch')return;const query=e.target.value.toLowerCase(),rows=[...app.querySelectorAll('[data-ledger-search]')];rows.forEach(row=>row.hidden=!row.dataset.ledgerSearch.includes(query));const count=app.querySelector('#ledgerResultCount');if(count)count.textContent=rows.filter(row=>!row.hidden).length+' / '+rows.length+(view==='history'?' events':' requests');});
